#pragma once

#define WIDTH 64
#define HEIGHT 64
#define PART_NUMBER 8
#define PART_LINE_NUMBER HEIGHT/PART_NUMBER

#define UNIT_BYTE 4
#define IN_WINDOW_SIZE WIDTH*UNIT_BYTE*3
#define OUT_WINDOW_SIZE WIDTH*UNIT_BYTE


