#pragma once

#define WIDTH 7680
#define HEIGHT 4320
#define PART_NUMBER 18
#define PART_LINE_NUMBER HEIGHT/PART_NUMBER

#define UNIT_BYTE 4
#define IN_WINDOW_SIZE WIDTH*UNIT_BYTE*3
#define OUT_WINDOW_SIZE WIDTH*UNIT_BYTE


